project_id = "devos-demo-338000"
region = "asia-northeast3"
zone = "asia-northeast3-a"
instance_name = "terraform-dave-instance"
instance_type = "e2-micro"
instance_image = "debian-cloud/debian-9"
vpc_name = "terraform-dave-network"