project_id = "opsnow-qa-automation"
region = "asia-northeast3"
zone = "asia-northeast3-a"
instance_name = "terraform-external-hi-instance"
instance_type = "e2-micro"
instance_image = "debian-cloud/debian-9"
vpc_name = "terraform-external-hi-network"
